name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 
      - name: Build docker image
        run: docker build -t mathimohamed/pipeline-cicd .
      - name: Publish image to docker hub
        run: docker push mathimohamed/pipeline-cicd:latest
        
  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Pull image from docker hub
        run: docker pull mathimohamed/pipeline-cicd:latest
      - name: Delete old container
        run: docker rm -f pipeline-cicd-container
      - name: Run docker container
        run: docker run -d -p 3000:3000 --name pipeline-cicd-container mathimohamed/pipeline-cicd
